language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
- PLONE_VERSION=4.2
- PLONE_VERSION=4.3
matrix:
  include:
  - python: 2.6
    env: PLONE_VERSION=4.0
  - python: 2.6
    env: PLONE_VERSION=4.1
  allow_failures:
  - python: 2.6
    env: PLONE_VERSION=4.0
  - python: 2.6
    env: PLONE_VERSION=4.1
  fast_finish: true
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage -t "--layer=!Robot"
- pip install -q coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
